### ISSUE TITLE
0.2 release roadmap

### ISSUE THREAD

**Issue by jakevdp** [mpld3/mpld3#108]
I'm talking about mpld3 at [OpenVisConf](http://openvisconf.com/) in late April, and I'd like to release version 0.2 before that.  Here is the list of what I'd like to have in the 0.2 release:
- [x] Javascript source refactored to use smash (see #104)
- [x] Start using vow to unit test javascript (depends on above refactoring in #104)
- [x] Clean up JS code, either with JSLint (#100) or with smash/uglify framework in #104 
- [x] Merge #102, making the HTML templates use anonymous functions
- [x] Make zoom and reset buttons into plugins; enable them by default (#114)
- [x] Add BoxZoom and LinkedBrush plugin into mpld3 python+JS library; enable BoxZoom by default (satisfied by #114 and #116)
- [x] Update examples which were broken by mpld3 JS refactoring
- [x] Fix issue with markers not appearing in legend (#48)
- [x] Add initial documentation on creating custom plugins (#147)
- [x] Add frequently asked questions
- [x] Add support for Python 3 (#117 & #134)
- [x] Add mouse position plugin (#142)

Pieces that probably won't happen at this point:
- [ ] Add single axis zoom behavior, following @jgbos example in #63 (potential solution in #112)
