### ISSUE TITLE
Tests: short-term and long-term TODO list

### ISSUE THREAD

**Issue by jakevdp** [mpld3/mpld3#137]
Just opening an issue to discuss testing.  There are a few things that would be nice to do, and some are easier than others
- [x] add Travis CI (thans @danielballan!)
- [x] improve python test coverage
- [x] figure out how to best include test plots & examples in nosetests
- [x] improve javascript test coverage
- [x] make Travis CI run javascript tests (requires setting up node.js, running npm install, and then running npm test) #139 
### And here are some harder ones
- [ ] create tests which combine Python & JS
- [ ] create automatic tests of user interaction: zooming, etc.

We can discuss various ideas here.
