### ISSUE TITLE
Documentation: short term and long-term roadmap

### ISSUE THREAD

**Issue by jakevdp** [mpld3/mpld3#138]
There are several places where the package documentation could be improved:
- [x] document the plugin interface. Perhaps add a notebook stepping through the process of creating a simple custom plugin?
- [ ] document the JSON plot representation. This would essentially be a list of parameter names, possible values, and meanings for each type of plot element
- [ ] document the mpld3 JS interface. A couple of people have been asking about this (cc @jgbos).

We can discuss related things here.
