### ISSUE TITLE
TODO list before 0.1 release

### ISSUE THREAD

**Issue by jakevdp** [mpld3/mpld3#49]
We're getting close to being able to release this in an 0.1 version on PyPI.

A few things I'd like to see before this happens (any others?)
- [x] Implement general marker types (see #37 and #38)
- [ ] Fix legend support (see #48)
- [ ] Fix line colors (see #47)
- [ ] Finalize plugin design (see https://github.com/jakevdp/mpld3/pull/43#commitcomment-5112302 and #50)
- [ ] Make HTML documentation & examples, especially for plugin framework (#54)

Other suggestions for must-have features or bug fixes?
